import type { Action, BotState } from "@arena/bot-contract";
import { describe, expect, it } from "vitest";
import { createNavigator } from "./index";
import { overheadTick50, overheadTick253 } from "./overheadBlock.fixtures";
import { planRoutes, SEARCH_LIMITS } from "./planner";
import { LANDING_MARGIN, predict, surfaces } from "./predictor";

describe("recorded overhead block stalls", () => {
  it("does not depend on level coordinates or object IDs", () => {
    const state = structuredClone(overheadTick50);
    state.position.x += 400;
    state.navigation!.body.x += 400;
    state.navigation!.viewport.x += 400;
    state.platforms.forEach((p, i) => {
      p.id = `surface-${i}`;
    });
    const routes = planRoutes(state);
    for (let i = 1; i * state.tuning.tickMs < 500 && routes.resume && !routes.options.length; i++)
      routes.resume();
    expect(routes.options.some((o) => o.route.goalProgressPx > 100)).toBe(true);
  });

  it("rejects the old retreat whose last held tick consumes the support margin", () => {
    const narrow = predict(overheadTick50, {
      aimX: 452,
      jump: false,
      holdMs: 0,
      direction: -1,
      sprint: false,
    });
    expect(narrow.safe).toBe(true);
    expect(narrow.landing!.marginPx).toBeCloseTo(8.00394074074029);
    const state = structuredClone(overheadTick50);
    state.platforms = state.platforms.filter((p) => p.collision === "solid");
    const routes = planRoutes(state);
    for (let i = 0; i < 16 && routes.resume; i++) routes.resume();
    expect(routes.options).toEqual([]);
  });
  it.each([overheadTick50, overheadTick253])(
    "offers supported progress from recorded tick $tick within the planning deadline",
    (state) => {
      const routes = planRoutes(state);
      for (
        let i = 1;
        i * state.tuning.tickMs < 500 && routes.resume && !routes.options.length;
        i++
      ) {
        expect(routes.stats.integrationSteps).toBeLessThanOrEqual(SEARCH_LIMITS.quantumSteps);
        routes.resume();
      }
      expect(routes.options.length).toBeGreaterThan(0);
      expect(routes.options.some((o) => o.route.goalProgressPx > 0)).toBe(true);
      expect([...routes.plans.values()].every((path) => path.every((leg) => leg.safe))).toBe(true);
    }
  );

  it.each(
    [overheadTick50, overheadTick253].flatMap((recorded) =>
      [-0.5, 0, 0.5].map((offset) => ({ recorded, tick: recorded.tick, offset }))
    )
  )(
    "executes and replans at decision boundaries without a retreat loop at tick $tick, offset $offset (predictor model)",
    ({ recorded, offset }) => {
      const state = structuredClone(recorded);
      state.navigation!.body.x += offset;
      const nav = createNavigator();
      const selected: string[] = [];
      const goalX = recorded.tick === 50 ? 784 : 1168;
      for (let i = 0; i < 300 && !(state.onGround && state.navigation!.body.x >= goalX); i++) {
        const actions = nav.decide(state);
        const diagnostic = nav.getDiagnostics();
        if (diagnostic.reason === "route-selected") selected.push(diagnostic.routeId!);
        expect(
          diagnostic.phase,
          JSON.stringify({ diagnostic, body: state.navigation!.body, selected })
        ).not.toBe("blocked");
        expect(
          diagnostic.phase,
          JSON.stringify({ diagnostic, body: state.navigation!.body, selected })
        ).not.toBe("recover");
        stepDecision(state, actions);
      }
      expect(state.navigation!.body.x, JSON.stringify(selected)).toBeGreaterThanOrEqual(goalX);
      expect(state.onGround).toBe(true);
      expect(selected.length).toBeLessThan(12);
    }
  );
});

// Execute the navigator's held actions, NOT its promised final coordinates.
// Each prefix is generated by the existing collision predictor. This is a
// closed-loop model regression, not a Phaser/worker timing integration test.
function stepDecision(state: BotState, actions: Action[]) {
  const n = state.navigation!;
  let remaining = Math.ceil(state.tuning.tickMs / n.physicsStepMs);
  while (remaining > 0) {
    const direction = actions.some((a) => a === "left" || a === "sprint-left")
      ? -1
      : actions.some((a) => a === "right" || a === "sprint-right")
        ? 1
        : 0;
    const prediction = predict(
      state,
      {
        aimX: n.body.x + n.body.width / 2 + direction * 10000,
        direction,
        sprint: actions.some((a) => a.startsWith("sprint")),
        jump: actions.includes("jump"),
        holdMs: 600,
      },
      remaining
    );
    expect(prediction.resume || prediction.safe, prediction.reason).toBeTruthy();
    expect(prediction.steps).toBeGreaterThan(0);
    remaining -= prediction.steps;
    const m = prediction.end;
    n.body = { ...m.body };
    state.velocity = { vx: m.vx, vy: m.vy };
    state.onGround = m.onGround;
    state.isSprinting = m.sprintMs > 0;
    state.sprintRampProgress = Math.min(1, m.sprintMs / state.tuning.sprintRampMs);
    n.movement.jumpStartedAtMs = m.jumpStartedAtMs;
    n.movement.impulseKind = m.impulseKind;
    n.observedAtMs += prediction.durationMs;
    n.frame += prediction.steps;
    state.timeElapsedMs += prediction.durationMs;
    state.coins = state.coins.filter((c) => !prediction.collectedIds.includes(c.id!));
    for (const hazard of state.hazards) {
      hazard.dx += (hazard.vx * prediction.durationMs) / 1000;
      hazard.dy += (hazard.vy * prediction.durationMs) / 1000;
      hazard.bounds!.dx += (hazard.vx * prediction.durationMs) / 1000;
      hazard.bounds!.dy += (hazard.vy * prediction.durationMs) / 1000;
    }
    if (state.onGround) {
      expect(
        surfaces(state).some(
          (p) =>
            Math.abs(p.y - m.body.y - m.body.height) < 1 &&
            m.body.x >= p.x + LANDING_MARGIN &&
            m.body.x + m.body.width <= p.x + p.width - LANDING_MARGIN
        ),
        JSON.stringify({ body: m.body, actions, tick: state.tick })
      ).toBe(true);
    }
  }
  const dx = n.body.x + n.body.width / 2 - state.position.x;
  const dy = n.body.y + n.body.height / 2 - state.position.y;
  state.position.x += dx;
  state.position.y += dy;
  state.goalDirection.dx -= dx;
  state.goalDirection.dy -= dy;
  for (const object of [...state.platforms, ...state.coins, ...state.hazards]) {
    object.dx -= dx;
    object.dy -= dy;
    if (object.bounds) {
      object.bounds.dx -= dx;
      object.bounds.dy -= dy;
    }
  }
  state.tick++;
}
