import type { BotState, NavigationObservation } from "@arena/bot-contract";

export const navigation: NavigationObservation = {
  version: 1,
  epoch: 2,
  frame: 10,
  observedAtMs: 160,
  physicsStepMs: 1000 / 60,
  body: { x: 0, y: 0, width: 24, height: 32 },
  movement: {
    jumpStartedAtMs: null,
    impulseKind: "none",
    impulseAtMs: null,
    sourceId: null,
  },
  viewport: { x: 0, y: 0, width: 400, height: 200 },
  boingoJumpVelocity: -700,
  stompJumpVelocity: -400,
};

export const sampleState: BotState = {
  tick: 42,
  position: { x: 0, y: 0 },
  facing: "right",
  onGround: true,
  isAlive: true,
  velocity: { vx: 0, vy: 0 },
  isSprinting: false,
  sprintRampProgress: 0,
  nearbyTiles: [],
  platforms: [],
  tuning: {
    gravity: 900,
    tileSize: 16,
    tickMs: 33,
    baseMoveSpeed: 200,
    sprintMoveSpeed: 320,
    sprintRampMs: 450,
    baseJumpVelocity: -560,
    sprintJumpVelocity: -650,
    minJumpHoldMs: 180,
    botWidth: 24,
    botHeight: 32,
  },
  nearestCoin: null,
  nearestHazard: null,
  nearestUtility: null,
  coins: [],
  hazards: [],
  utilities: [],
  goalDirection: { dx: 1, dy: 0 },
  gapAhead: { present: false, distance: null },
  worldBounds: { width: 400, height: 200 },
  justRespawned: false,
  tookDamage: false,
  coinsCollected: 0,
  livesRemaining: 3,
  timeElapsedMs: 160,
};
